services:
  question:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./QuestionService:/QuestionService
    env_file:
      - .env
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - q_db
  q_db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}