# Generated by Django 5.0 on 2024-01-04 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Вопрос опроса',
                'verbose_name_plural': 'Вопросы опросов',
            },
        ),
        migrations.CreateModel(
            name='OptionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.questionsurvey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Ответ на опрос',
                'verbose_name_plural': 'Ответы на опросы',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вопроса')),
                ('q_amount', models.PositiveIntegerField(default=1, verbose_name='Количество вопросов')),
                ('description', models.TextField(verbose_name='Описание опроса')),
                ('pic', models.ImageField(blank=True, upload_to='static/images/%Y/%m/%d/', verbose_name='Картинка теста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.AddField(
            model_name='questionsurvey',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.survey', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='SurveyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_options', models.ManyToManyField(to='Survey.optionsurvey', verbose_name='Ответы')),
                ('contender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проходящий')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.survey', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Попытка прохождения опроса',
                'verbose_name_plural': 'Попытки прохождений опросов',
            },
        ),
    ]
