# Generated by Django 5.0 on 2024-01-04 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('multiple_correct', models.BooleanField(default=False, verbose_name='Несколько правильных ответов')),
                ('multiple_answers', models.BooleanField(default=False, verbose_name='Несколько ответов для засчёта')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы тестов',
            },
        ),
        migrations.CreateModel(
            name='OptionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('correct', models.BooleanField(default=False, verbose_name='Правильность опции')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.questiontest', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа теста',
                'verbose_name_plural': 'Варианты ответов тестов',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вопроса')),
                ('q_amount', models.PositiveIntegerField(default=1, verbose_name='Количество вопросов')),
                ('question_amount', models.IntegerField(default=0, verbose_name='Количество вопросов')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='questiontest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test', verbose_name='Опрос'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveIntegerField(default=0, verbose_name='Результат')),
                ('chosen_options', models.ManyToManyField(to='Test.optiontest', verbose_name='Выбранные ответы')),
                ('contender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Проходящий')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.test', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
            },
        ),
    ]
